// Generated by tools/gen_sprites.py - do not edit by hand.
#ifndef LFN_TILES_H
#define LFN_TILES_H

namespace lfn::tile
{
    // A metatile is 16x16, so it owns four 8x8 tiles:
    //   TL = m*4 + 0, TR = m*4 + 1, BL = m*4 + 2, BR = m*4 + 3
    constexpr int size = 16;
    constexpr int count = 16;

    constexpr int empty = 0;
    constexpr int ground_top = 1;
    constexpr int ground_fill = 2;
    constexpr int block = 3;
    constexpr int breakable = 4;
    constexpr int platform = 5;
    constexpr int spikes = 6;
    constexpr int ledge_l = 7;
    constexpr int ledge_r = 8;
    constexpr int pillar = 9;
    constexpr int decor = 10;
    constexpr int bg_a = 11;
    constexpr int bg_b = 12;
    constexpr int door = 13;
    constexpr int chain = 14;
    constexpr int hazard = 15;

    constexpr const char* world_keys[] = {
        "pride",
        "greed",
        "lust",
        "envy",
        "gluttony",
        "wrath",
        "sloth",
        "hades",
    };
}

#endif
