#!/usr/bin/env python3
"""
Compile levels/*.txt into include/lfn_levels.h.

Entity characters are lifted out of the grid and become spawn records, so a
level file stays a single readable picture of the stage.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import art_tiles as T
import level_kit as K

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVELS = os.path.join(ROOT, 'levels')
OUT = os.path.join(ROOT, 'include', 'lfn_levels.h')

TERRAIN = {
    K.EMPTY: T.EMPTY, K.GROUND: T.GROUND_TOP, K.FILL: T.GROUND_FILL,
    K.BLOCK: T.BLOCK, K.BREAK: T.BREAKABLE, K.PLAT: T.PLATFORM,
    K.SPIKE: T.SPIKES, K.LEDGE_L: T.LEDGE_L, K.LEDGE_R: T.LEDGE_R,
    K.PILLAR: T.PILLAR, K.LAMP: T.DECOR, K.BG_A: T.BG_A, K.BG_B: T.BG_B,
    K.DOOR: T.DOOR, K.CHAIN: T.CHAIN, K.LAVA: T.HAZARD,
}

# Order here defines the C++ enum, so the engine and the levels agree.
SPAWNS = [
    ('player', K.PLAYER), ('exit', K.EXIT), ('checkpoint', K.CHECKPOINT),
    ('boss', K.BOSS), ('warp', K.WARP), ('sign', K.SIGN),
    ('imp', K.IMP), ('cherub', K.CHERUB), ('gnasher', K.GNASHER),
    ('wraith', K.WRAITH), ('bat', K.BAT), ('jet', K.JET),
    ('pu_flame', K.PU_FLAME), ('pu_soul', K.PU_SOUL), ('pu_dash', K.PU_DASH),
    ('pu_wings', K.PU_WINGS), ('one_up', K.ONE_UP), ('soul', K.SOUL),
]
SPAWN_INDEX = {ch: i for i, (name, ch) in enumerate(SPAWNS)}

MUSIC = ['title', 'w1_pride', 'w2_greed', 'w3_lust', 'w4_envy', 'w5_gluttony',
         'w6_wrath', 'w7_sloth', 'w8_hades', 'boss', 'victory', 'game_over']


def parse(path):
    meta, rows = {}, []
    for line in open(path):
        line = line.rstrip('\n')
        if line.startswith('!'):
            if ':' in line:
                k, v = line[1:].split(':', 1)
                meta[k.strip()] = v.strip()
            continue
        if line:
            rows.append(line)
    if len(rows) != K.ROWS:
        raise ValueError('%s: expected %d rows, found %d'
                         % (path, K.ROWS, len(rows)))
    width = max(len(r) for r in rows)
    # The GBA wants bg maps sized in whole 32-cell blocks, and one metatile is
    # two cells, so level width is padded up to a multiple of 16 metatiles.
    width = ((width + 15) // 16) * 16
    rows = [r.ljust(width, K.BG_A) for r in rows]

    prize_of = {block: pickup for pickup, block in K.PRIZE_BLOCKS.items()}

    spawns, tiles = [], []
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in K.PRIZE_CHARS:
                # Both a spawn and a solid block: the engine keeps the pickup
                # sealed until that block is broken open.
                spawns.append((SPAWN_INDEX[prize_of[ch]], x, y))
                ch = K.BREAK
            elif ch in K.ENTITY_CHARS:
                spawns.append((SPAWN_INDEX[ch], x, y))
                ch = K.BG_A
            if ch not in TERRAIN:
                raise ValueError('%s: unknown character %r at %d,%d'
                                 % (path, ch, x, y))
            tiles.append(TERRAIN[ch])

    if not any(s[0] == SPAWN_INDEX[K.PLAYER] for s in spawns):
        raise ValueError('%s: no player start' % path)
    boss = int(meta.get('boss', 0))
    warp = int(meta.get('warp', -1))
    exit_to = int(meta.get('exit_to', -1))
    hidden = int(meta.get('hidden', 0))
    secret = meta.get('secret', '')

    if not boss and not any(s[0] == SPAWN_INDEX[K.EXIT] for s in spawns):
        raise ValueError('%s: no exit gate' % path)

    if boss and not any(s[0] == SPAWN_INDEX[K.BOSS] for s in spawns):
        raise ValueError('%s: boss stage with no boss' % path)

    return {
        'key': os.path.basename(path)[:-4],
        'name': meta.get('name', '?'),
        'world': int(meta.get('world', 0)),
        'music': MUSIC.index(meta.get('music', 'w1_pride')),
        'width': width,
        'tiles': tiles,
        'spawns': spawns,
        'boss': boss,
        'warp': warp,
        'exit_to': exit_to,
        'hidden': hidden,
        'secret': secret,
    }


def main():
    files = sorted(f for f in os.listdir(LEVELS) if f.endswith('.txt'))
    levels = [parse(os.path.join(LEVELS, f)) for f in files]

    # Story stages keep their order and their indices; hidden rooms go after
    # them, so adding a secret room can never renumber the game.
    levels.sort(key=lambda lv: (lv['hidden'], lv['key']))

    out = ['// Generated by tools/build_levels.py - do not edit by hand.',
           '#ifndef LFN_LEVELS_H', '#define LFN_LEVELS_H', '',
           '#include <cstdint>', '', 'namespace lfn', '{', '    namespace spawn_type', '    {']
    for i, (name, ch) in enumerate(SPAWNS):
        out.append('        constexpr uint8_t %s = %d;' % (name, i))
    out += ['    }', '',
            '    constexpr int level_rows = %d;' % K.ROWS,
            '',
            '    struct spawn_point',
            '    {',
            '        uint8_t type;',
            '        uint16_t x;',
            '        uint8_t y;',
            '    };', '',
            '    struct level_data',
            '    {',
            '        const char* name;',
            '        const uint8_t* tiles;      // columns * level_rows, row major',
            '        const spawn_point* spawns;',
            '        uint16_t columns;',
            '        uint16_t spawn_count;',
            '        uint8_t world;',
            '        uint8_t music;',
            '        uint8_t boss;      // 0 for a normal stage, else which sin',
            '        int16_t warp;      // where a warp door here leads, -1 for none',
            '        int16_t exit_to;   // where the exit gate leads, -1 for the next stage',
            '        uint8_t hidden;    // kept out of the story order and stage select',
            '        const char* secret;  // writing shown at the sign marker',
            '    };', '']

    for lv in levels:
        out.append('    inline constexpr uint8_t %s_tiles[] = {' % lv['key'])
        for y in range(K.ROWS):
            row = lv['tiles'][y * lv['width']:(y + 1) * lv['width']]
            out.append('        ' + ','.join(str(v) for v in row) + ',')
        out.append('    };')
        out.append('    inline constexpr spawn_point %s_spawns[] = {' % lv['key'])
        for t, x, y in lv['spawns']:
            out.append('        {%d, %d, %d},' % (t, x, y))
        out.append('    };')
        out.append('')

    out.append('    inline constexpr level_data levels[] = {')
    for lv in levels:
        out.append('        {"%s", %s_tiles, %s_spawns, %d, %d, %d, %d, %d, %d, %d, %d, %s},'
                   % (lv['name'], lv['key'], lv['key'], lv['width'],
                      len(lv['spawns']), lv['world'], lv['music'], lv['boss'],
                      lv['warp'], lv['exit_to'], lv['hidden'],
                      ('"%s"' % lv['secret']) if lv['secret'] else 'nullptr'))
    out.append('    };')
    out.append('    constexpr int level_count = %d;' % len(levels))
    story = sum(1 for lv in levels if not lv['hidden'])
    out.append('    // Stages the story runs through; the rest are secret rooms.')
    out.append('    constexpr int story_count = %d;' % story)
    out += ['}', '', '#endif', '']

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('\n'.join(out))

    total = sum(lv['width'] for lv in levels)
    print('compiled %d levels, %d columns total, %.1f KB of tile data'
          % (len(levels), total, total * K.ROWS / 1024.0))
    for lv in levels:
        print('  %-14s %-26s w=%3d  spawns=%3d'
              % (lv['key'], lv['name'], lv['width'], len(lv['spawns'])))


if __name__ == '__main__':
    main()
